spring:
  application:
    name: processing-service
server:
  port: 8182

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
        exclude: beans
  endpoint:
    health:
      show-details: always
      env:
        show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    uu.app: debug
  file:
    name: logs/processing-service.log
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"

simulation:
  delay-ms: 0
  percent-of-failure: 0

service:
  connection:
    repository-service:
      host: localhost
      port: 8181
