spring:
  application:
    name: processing-service
server:
  port: 8182

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    health:
      show-details: always
      env:
        show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
