spring:
  application:
    name: client-service
  task:
    execution:
      pool:
        size: 10
server:
  port: 8183

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
        exclude: beans
  endpoint:
    health:
      show-details: always
      env:
        show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    uu.app: debug
  file:
    name: logs/client-service.log
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"

service:
  connection:
    processing-service:
      host: localhost
      port: 8182

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}