spring:
  application:
    name: registry-service
server:
  port: 8184

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    health:
      show-details: always
      env:
        show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    uu.app: debug
  file:
    name: logs/registry-service.log
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"